[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "680c2a594cc89e92e57ebf2e5f63ce143f22534a"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "26edb16a47cd94144c70a87388fc4eec340c6eac5ae32f9dcb31e38f1e19db01"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2022.2.1+0/MKL_Headers.v2022.2.1.i686-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "6be4c71e7bcc5fd19a9d65b40c5373f1b00ec2ed"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "b6722fcf4f48c30e32a079c5dfcdefb702440b7c9f5c32093986facfe44850b0"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2022.2.1+0/MKL_Headers.v2022.2.1.i686-w64-mingw32.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "26ec08601c0f1097bd35263d9f59b295e85bd819"
os = "macos"

    [[MKL_Headers.download]]
    sha256 = "c030c6449c765fff9471eac38722df5cda9ba00183ff8986e1f1f9ba5fd46499"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2022.2.1+0/MKL_Headers.v2022.2.1.x86_64-apple-darwin.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "20b1a860029d4eb5d4238409fccb73903c623c1b"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "afc62bded6286a21b1d71a6faa5d295a2895283be90fa5e2f884d5812d0b6576"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2022.2.1+0/MKL_Headers.v2022.2.1.x86_64-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "03d6410674251a0d8c9fdde9340ac6a618ce74df"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "8a1cb6171477f84bbc65cd4641246f0ebfc61389a709a19faf29e4b886b0fb07"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2022.2.1+0/MKL_Headers.v2022.2.1.x86_64-w64-mingw32.tar.gz"
