[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "c091e412667a5a34f1511d54ccfd2587dfcce2d6"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "c812d0c0b65a14cb652f438a8ab0eaf8f9e2bc920d2bc97a2c0f12d3487446ac"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.2.0+0/MKL_Headers.v2023.2.0.i686-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "bc12485fa8fadf983362e422d9fc0d614dd79177"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "f7982065e6d5d3962934f270432b1b53e4e3cef03f600e1a2e1ddfa4fea0be82"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.2.0+0/MKL_Headers.v2023.2.0.i686-w64-mingw32.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "624fd529a7e646989dd1115cd396e2860a12efb0"
os = "macos"

    [[MKL_Headers.download]]
    sha256 = "ef44bc4229cf977770b39883c37d067551ff8aed3a9e665e364161785770d66f"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.2.0+0/MKL_Headers.v2023.2.0.x86_64-apple-darwin.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "b05be6fb823a59ec0d0f7b6d8746e3d6d82cd21f"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "73fb4c22a816745ae4f00bec8695d403e1720098f17ea2896e09ffcac6bdbd35"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.2.0+0/MKL_Headers.v2023.2.0.x86_64-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "e22de2fd7fda8826ccd96f86031c98e2cd5de982"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "6cca2791bf9dc007ca6e41eb88db2b7694b38a4de0c25c4f99ff8f628cac97be"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.2.0+0/MKL_Headers.v2023.2.0.x86_64-w64-mingw32.tar.gz"
