[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "ea46ed920500b7ace532dd9cf39dac66963e4874"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "2b2b0d27c1c6437614d5c191934e8fc7e63c83c719ba28537a803e9af23a2eda"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.1.0+0/MKL_Headers.v2023.1.0.i686-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "25f4af9a17810ac6264dd94c56e7bee4c8736f88"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "4409531d02f27b853f23734ec5d4c452e07e9096349e34ac102a7d1d98fabe95"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.1.0+0/MKL_Headers.v2023.1.0.i686-w64-mingw32.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "67a47c2c9d09ebd6534e6eb945c6c87c19bcf877"
os = "macos"

    [[MKL_Headers.download]]
    sha256 = "7d72952b086519a5bd57c4c4c4c8bed56e7fc9f6c395cc5a259a9732cb418586"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.1.0+0/MKL_Headers.v2023.1.0.x86_64-apple-darwin.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "b79565a6bed57e6c0c66ec2580145349a240c9f1"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "2efc858594a8c26f9c89bcdec78508eb0f3b157c38d99dc0d9018c29f1b6ab59"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.1.0+0/MKL_Headers.v2023.1.0.x86_64-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "0608026f887e4d43d3e9920d7d4e01894519675e"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "3c13a362b34204cb77f7c70ff26abe93ebc0160af9a278d1735d0f519fc81526"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2023.1.0+0/MKL_Headers.v2023.1.0.x86_64-w64-mingw32.tar.gz"
