[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "ca63e3c6b750c28e5dc173202969ace904f02b8b"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "d45a610af9d338e75191098a17212aec47d6ae83a114503c0cbcd77fe489054f"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.2.0+0/MKL_Headers.v2024.2.0.i686-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "3b41ff50c3a1e9d0a2f518963fd1f2b8e9389edd"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "20c415fe6c5fe16722f81f387a8e2f6bd97363b387f1dcaaf961d6449f49507e"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.2.0+0/MKL_Headers.v2024.2.0.i686-w64-mingw32.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "8c2b4cf830e0af8d3edd8dc3e14b3d6d5c7d2ca4"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "ae140e22da70009ce55f973ea2d8c56b39434e091f1dd0de583733a5b1740f02"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.2.0+0/MKL_Headers.v2024.2.0.x86_64-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "9f97c8b62e9e59789dc37d5a2c69edecc670e3cd"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "c732df7b6c49819b381b9b599d53678cd4a2798128be35ec4c14faa3b807f3d6"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.2.0+0/MKL_Headers.v2024.2.0.x86_64-w64-mingw32.tar.gz"
