[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "5adf7e845b65103f7d109b1acc826495300aec65"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "5cda1dd5b733b4c5926fcd954117a40f15525f958db96269e12ec228728877c4"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.1.0+0/MKL_Headers.v2024.1.0.i686-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "i686"
git-tree-sha1 = "fd0833af1b2fbeefe2dae6fb39c059f6273f6280"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "e4ff423f155e3f8d62eaa22e9c364b7da79350bb0b05910ee4006dbeaff659eb"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.1.0+0/MKL_Headers.v2024.1.0.i686-w64-mingw32.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "270e6a9888f7b25f48f55f62159add299bff1c6c"
libc = "glibc"
os = "linux"

    [[MKL_Headers.download]]
    sha256 = "f978e8cbac566bab0e075c784140864b3ac03ca124170998c8e739ce49df3da3"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.1.0+0/MKL_Headers.v2024.1.0.x86_64-linux-gnu.tar.gz"
[[MKL_Headers]]
arch = "x86_64"
git-tree-sha1 = "bc25b499ee667e0eac9b0789449c21ee6eaca51c"
os = "windows"

    [[MKL_Headers.download]]
    sha256 = "d2cae98d1628f370cbbd6f3cd5e62a5c287f2ed4441385e26e87c02482ffff06"
    url = "https://github.com/JuliaBinaryWrappers/MKL_Headers_jll.jl/releases/download/MKL_Headers-v2024.1.0+0/MKL_Headers.v2024.1.0.x86_64-w64-mingw32.tar.gz"
